PENDING = "PENDING"
SUBMITTED = "SUBMITTED"
RUNNING = "RUNNING"
FAILED = "FAILED"
KILLED = "KILLED"
SUCCEEDED = "SUCCEEDED"
FINISHED = "FINISHED"


class ExecutionStatus:

    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"